services:
  stt:
    build:
      context: ./stt
    container_name: stt
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      MODEL_NAME: sherpa-onnx-cohere-transcribe-14-lang-int8-2026-04-01
      MODEL_DIR: /models/sherpa-onnx-cohere-transcribe-14-lang-int8-2026-04-01
      VAD_MODEL: /models/silero_vad.onnx
      SHERPA_NUM_THREADS: "3"
      DECODE_MAX_CONCURRENCY: "1"
      UVICORN_WORKERS: "1"
      SAMPLE_RATE: "16000"
      FEATURE_DIM: "80"
      MODEL_LANGUAGE: pt
      MODEL_TYPE: cohere_transcribe_offline_vad_streaming
      USE_INTERNAL_VAD: "true"
      AUTO_DOWNLOAD_MODEL: "1"
      LOG_LEVEL: INFO
    volumes:
      - ./stt/models:/models
    tmpfs:
      - /tmp:size=256m
